# --- !Ups
DELETE FROM vocable;
INSERT INTO `vocable` (`question`, `answer`, `category_id`)
  VALUES
  -- Phrases
  ('Good morning','おはよう',1),
  ('Good morning (polite)','おはよう　ございます',1),
  ('Good afternoon','こんいちは',1),
  ('Good evening','こんばんは',1),
  ('Good bye','さようなら',1),
  ('Good night','おやすみなさい',1),
  ('Thank you','ありがとう',1),
  ('Thank you (polite)','ありがとう　ございます',1),
  ('Excuse me / I´m sorry','すみません',1),
  ('No / Not at all','いいえ',1),
  ('I´ll go and come back','いってきます',1),
  ('Please go and come back','いってらしゃい',1),
  ('I´m home','ただいま',1),
  ('Wecome home','おかえりなさい',1),
  ('Thank you for the meal (before eating)','いただきます',1),
  ('Thank you for the meal (after eating)','ごちそうさまでした',1),
  ('How do you do?','はじめまして',1),
  ('Nice to meet you','よろしくおねがいします',1),
  ('Um...','あの',1),
  ('Yes','はい',1),
  ('That´s right','そです',1),
  ('I see / Is that so?','そですか',1),
  ('What','なん/なに',1),
  ('Delicious','おいしい',1),
  ('How much','いくら',1),
  ('Expensive / High','たかい',1),
  ('Welcome (to our store)','いらっしゃいません',1),
  ('..., please','(~を)おねがいします',1),
  ('Please give me...','(~を)ください',1),
  ('then... / if that is the case...','じゃあ',1),
  ('Please / Here it is','どうぞ',1),
  ('Thank you','どうも',1),
  ('Do you understand?','わかりましたか',1),
  ('I understand / I understood','わかりました',1),
  ('I don´t understand / I don´t know','わかりません',1),
  ('Please say it slowly','ゆっくりいってください',1),
  ('Please say it again','もういちどいってください',1),
  ('Please wait','ちょっとまってください',1),
  ('Please listen / Please ask','きいてください',1),
  ('Please look at page 10','じゅぺえじをみてください',1),
  ('That´s right / Le me see','そうですね',1),
  ('But','でも',1),
  ('How about ...? / How is ...?','どうですか',1),
  ('I´m sorry','ごめんなさい',1),
  ('Why','どうして',1),
  ('And then','それから',1),
  ('It´s okay / Not to worry / Everything is under control','だいじょうぶ',1),
  ('What kind of...','どんな',1),
  ('Because','~から',1),
  ('That would be fine / That wouldn´t be necessarry','けっこうです',1),
  ('Right away','すぐ',1),
  ('Really?','ほんとうですか',1),
  ('Slowly / Leisure / Unhurriedly','ゆっくり',1),

  -- Vocabulary
  ('Now','いま',2),
  ('English (language)','えいご',2),
  ('... language','ご',2),
  ('P.M.','ごご',2),
  ('A.M.','ごぜん',2),
  ('... years old','さい',2),
  ('Mr. / Mrs.','さん',2),
  ('O´clock','じ',2),
  ('People','じん',2),
  ('Major','せんこう',2),
  ('... year student','ねんせい',2),
  ('Half','はん',2),
  ('... yen','~えん',2),
  ('Mountain','やま',2),
  ('River','かわ',2),
  ('Fine','けんきな',2),
  ('Rice field','た',2),
  ('Spirit','き',2),
  ('Origin','けん',2),
  ('Woman','おんな',2),
  ('Man','おとこ',2),
  ('East','ひがし',2),
  ('West','にし',2),
  ('South','みなみ',2),
  ('North','きた',2),
  ('Mouth','くち',2),
  ('Exit','でぐち',2),
  ('Foreign country','がいこく',2),
  ('Foreigner','がいこくじん',2),

  -- Nouns
  ('Student','がくせい',3),
  ('High scool','こおこお',3),
  ('College / University','だいがく',3),
  ('Telephone','でんわ',3),
  ('Friend','ともだち',3),
  ('Name','なまえ',3),
  ('Japan','にほん',3),
  ('Number','ばんごう',3),
  ('International student','りょうがくせい',3),
  ('Teacher / Professor','セんせい',3),
  ('I','わたし',3),
  ('Job / work / occupation','しごと',3),
  ('Doctor','いしゃ',3),
  ('Office worker','かいしゃいん',3),
  ('High school student','こうこうせい',3),
  ('Housewife','しゅふ',3),
  ('Graduate student','だいがくいんせい',3),
  ('College student','だいがくせい',3),
  ('Lawyer','べんごし',3),
  ('Mother','おかあさん',3),
  ('Father','おとうさん',3),
  ('Older sister','おねえさん',3),
  ('Older brother','おにいさん',3),
  ('Younger sister','いもうと',3),
  ('Younger brother','おとうと',3),
  ('Fish','さかな',3),
  ('Pork cutlet','とんかつ',3),
  ('Meat','にく',3),
  ('Menu','メニュー',3),
  ('Vegetable','やさい',3),
  ('Pencil','えんぴつ',3),
  ('Umbrella','かさ',3),
  ('Bag','かばん',3),
  ('Shoes','くつ',3),
  ('Wallet','さいふ',3),
  ('Jeans','ジーンズ',3),
  ('Dictionary','じしょ',3),
  ('Bicycle','じてんしゃ',3),
  ('Newspaper','しんぶん',3),
  ('T-shirt','Tシャツ',3),
  ('Watch / clock','とけい',3),
  ('Notebook','ノート',3),
  ('Pen','ぺん',3),
  ('Hat / Cap','ぼうし',3),
  ('Book','ほん',3),
  ('Cafe','きっさてん',3),
  ('Bank','ぎんこう',3),
  ('Toilet / Restroom','トイレ',3),
  ('Library','としょかん',3),
  ('Post office','ゆうびんきょく',3),
  ('Movie','えいが',3),
  ('Music','おんがく',3),
  ('Magazine','ざっし',3),
  ('Sports','スポーツ',3),
  ('Date (romantic)','デート',3),
  ('Tennis','テニス',3),
  ('TV','テレビ',3),
  ('Ice cream','アイスクリーム',3),
  ('Sake / Alcohol','おさけ',3),
  ('Green tea','おちゃ',3),
  ('Coffee','コーヒー',3),
  ('Dinner','ばんごはん',3),
  ('Hamburger','ハンバーガー',3),
  ('Lunch','ひるごはん',3),
  ('Water','みず',3),
  ('Home / House','いえ',3),
  ('Home / House / My place','うち',3),
  ('School','かっこう',3),
  ('Part-time job','アリバイト',3),
  ('Shopping','かいもの',3),
  ('Class','クラス',3),
  ('You','あなた',3),
  ('Chair','いす',3),
  ('Dog','いぬ',3),
  ('Souvenir','おみやげ',3),
  ('Child','こども',3),
  ('Rice / Meal','ごはん',3),
  ('Picture / Photograph','しゃしん',3),
  ('Desk','つくえ',3),
  ('Letter','てがみ',3),
  ('Cat','ねこ',3),
  ('Bread','パン',3),
  ('Person','ひと',3),
  ('E-mail','メール',3),
  ('Temple','おてら',3),
  ('Park','こうえん',3),
  ('Supermarket','スーパー',3),
  ('Department store','デパート',3),
  ('Bus stop','バスてい',3),
  ('Hospital','びょういん',3),
  ('Hotel','ホテル',3),
  ('Book store','ほんや',3),
  ('Town / City','まち',3),
  ('Resturant','レストラン',3),
  ('Sea','うみ',3),
  ('Postal stamps','きって',3),
  ('Ticket','きっぷ',3),
  ('Surfing','サーフィン',3),
  ('Homework','しゅくだい',3),
  ('Food','たべもの',3),
  ('Birthday','たんじょうび',3),
  ('Test','テスト',3),
  ('Drink','のみもの',3),
  ('Postcard','はがき',3),
  ('Bus','バス',3),
  ('Airplane','ひこうき',3),
  ('Room','へや',3),
  ('I (used by men)','がく',3),
  ('Holiday / Day off / Absence','やすみ',3),
  ('Travel','りょこう',3),
  ('Money','おかね',3),
  ('Bath','おふろ',3),
  ('Kanji / Chinese character','かんじ',3),
  ('Textbook','きょうかしょ',3),
  ('This week','こんしゅう',3),
  ('Municipal hospital','しみんびょういん',3),
  ('Shower','シャワー',3),
  ('Next','つぎ',3),
  ('Electricity','でんき',3),
  ('Train','でんしゃ',3),
  ('Baggage','にもつ',3),
  ('Page','ページ',3),
  ('Window','もど',3),
  ('Night','よる',3),
  ('Shop / Store','みせ',3),
  ('Sweet bun','おまんしゅう',3),
  ('Castle','おしろ',3),
  ('Station','えき',3),
  ('Everyone','みなさん',3),
  ('Cooking / Dish','りょうり',3),
  ('Chef','シェフ',3),
  ('Wine','ワイン',3),
  ('Pizza','ピザ',3),


  -- Countries
  ('U.S.A.','アメリカ',4),
  ('Britain','イギリス',4),
  ('Australia','オーストラリア',4),
  ('Korea','かんこく',4),
  ('Sweden','スウェーデン',4),
  ('China','ちゅうごく',4),
  ('Mexico','メキシコ',4),
  ('Italy','イタリア',4),

  -- Majors
  ('Science','かがく',5),
  ('Asian studies','アジアけんきゅう',5),
  ('Economics','けいざい',5),
  ('International relations','こくさいかんけい',5),
  ('Computer','コンピューター',5),
  ('Anthropology','じんるいがく',5),
  ('Politics','せいじ',5),
  ('Business','ビジネス',5),
  ('Literature','ぶんがく',5),
  ('History','れきし',5),

  -- Time & Age
  ('1 O´clock','いちじ',6),
  ('2 O´clock','にじ',6),
  ('3 O´clock','さんじ',6),
  ('4 O´clock','よじ',6),
  ('5 O´clock','ごじ',6),
  ('6 O´clock','ろくじ',6),
  ('7 O´clock','しちじ',6),
  ('8 O´clock','はちじ',6),
  ('9 O´clock','くじ',6),
  ('10 O´clock','じゅうじ',6),
  ('11 O´clock','じゅういちじ',6),
  ('12 O´clock','じゅうにじ',6),
  ('1 minute','いっぷん',6),
  ('2 minutes','にふん',6),
  ('3 minutes','さんぷん',6),
  ('4 minutes','よんぷん',6),
  ('5 minutes','ごふん',6),
  ('6 minutes','ろっぷん',6),
  ('7 minutes','ななふん',6),
  ('8 minutes','はっぷん/はちふん',6),
  ('9 minutes','きゅうふん',6),
  ('10 minutes','じゅっぷん/じっぷん',6),
  ('11 minutes','じゅういっぷん',6),
  ('12 minutes','じゅうにふん',6),
  ('13 minutes','じゅうさんぷん',6),
  ('14 minutes','じゅうよんぷん',6),
  ('15 minutes','じゅうごふん',6),
  ('16 minutes','じゅうろっぷん',6),
  ('17 minutes','じゅうななふん',6),
  ('18 minutes','じゅうはっぷん/じゅうはちふん',6),
  ('19 minutes','じゅうきゅうふん',6),
  ('20 minutes','にじゅうぷん',6),
  ('30 minutes','さんじっぷん',6),
  ('1 year old','いっさい',6),
  ('2 years old','にさい',6),
  ('3 years old','さんさい',6),
  ('4 years old','よんさい',6),
  ('5 years old','ごさい',6),
  ('6 years old','ろくさい',6),
  ('7 years old','ななさい',6),
  ('8 years old','はっさい',6),
  ('9 years old','きゅうさい',6),
  ('10 years old','じゅっさい/じっさい',6),
  ('11 years old','じゅういっさい',6),
  ('20 years old','はたち/にじゅうさい/にじっさい',6),

  -- Location words
  ('This one','これ',7),
  ('That one','それ',7),
  ('That one (over there)','あれ',7),
  ('Which one','どれ',7),
  ('This...','この',7),
  ('That...','その',7),
  ('That... (over there)','あの',7),
  ('Which...','どの',7),
  ('Here','ここ',7),
  ('There','そこ',7),
  ('Over there','あそこ',7),
  ('Where','どこ',7),
  ('Who','だれ',7),
  ('Right','みぎ',7),
  ('Left','ひだり',7),
  ('Front','まえ',7),
  ('Back','うしろ',7),
  ('Inside','なか',7),
  ('On','うえ',7),
  ('Under','した',7),
  ('Near / Nearby','ちかく',7),
  ('Next','となり',7),
  ('Between','あいだ',7),

  -- Time expressions
  ('Morning','あさ',8),
  ('Tomorrow','あした',8),
  ('When','いつ',8),
  ('Today','きょう',8),
  ('At about...','~ごろ',8),
  ('Tonight','こんばん',8),
  ('Weekend','しゅうまつ',8),
  ('Saturday','どようび',8),
  ('Sunday','にちようび',8),
  ('Every day','まいにち',8),
  ('Every night','まいばん',8),
  ('Yesterday','きのう',8),
  ('...hours','じかん',8),
  ('One our','いちじかん',8),
  ('Last week','せんしゅう',8),
  ('When... / At the time of...','とき',8),
  ('Monday','げつようび',8),
  ('Tuesday','かようび',8),
  ('Wednesday','すいようび',8),
  ('Thursday','もくようび',8),
  ('Friday','きにようび',8),
  ('Next week','らいしゅう',8),
  ('Next year','らいねん',8),
  ('Night','よる',8),
  ('Again','また',8),


  -- Verbs
  ('To go','いく (u)',9),
  ('To go back / to return','かえる (u)',9),
  ('To listen','きく (u)',9),
  ('To drink','のむ (u)',9),
  ('To speak / To talk','はなす (u)',9),
  ('To read','よむ (u)',9),
  ('To get up','おきる (ru)',9),
  ('To eat','たべる (ru)',9),
  ('To sleep / To go to sleep','ねる (ru)',9),
  ('To see / Look at / To watch','みる (ru)',9),
  ('To come','くる (irr)',9),
  ('To do','する (irr)',9),
  ('To study','べんきょうする (irr)',9),
  ('To meet / To see','あう (u)',9),
  ('There is...','ある (u)',9),
  ('To buy','かう (u)',9),
  ('To write','かく (u)',9),
  ('To take (a picture)','どる (u)',9),
  ('To wait','まつ (u)',9),
  ('To understand','わかる (u)',9),
  ('(A person) is in... / stays at...','いる (ru)',9),
  ('To go out','てかける (ru)',9),
  ('To swim','およぐ (u)',9),
  ('To ask','きく (u)',9),
  ('To ride / To board','のる (u)',9),
  ('To do / To perform','やる (u)',9),
  ('To play / To spend time pleasantly','あすぶ (u)',9),
  ('To hurry','いそぐ (u)',9),
  ('To take a bath','おふらにはいる (u)',9),
  ('To return (a thing)','かえす (u)',9),
  ('To turn off / To erase','けす (u)',9),
  ('To die','しぬ (u)',9),
  ('To sit down','すわる (u)',9),
  ('To stand up','たつ (u)',9),
  ('To smoke','たばこをすう (u)',9),
  ('To use','つかう (u)',9),
  ('To help','てつだう (u)',9),
  ('To enter','はいる (u)',9),
  ('To carry / To hold','もつ (u)',9),
  ('To be absent (from...) / To rest','やすむ (u)',9),
  ('To open (something)','あける (ru)',9),
  ('To teach / To instruct','おしえる (ru)',9),
  ('To get off','おりる (ru)',9),
  ('To borrow','かりる (ru)',9),
  ('To close (something)','しめる (ru)',9),
  ('To take a shower','シャワーをあびる (ru)',9),
  ('To turn on','つける (ru)',9),
  ('To make a phone call','でんわをかける (ru)',9),
  ('To forget / To leave behind','わすれる (ru)',9),
  ('To bring (a person)','つれてくる (irr)',9),
  ('To bring (a thing)','もってくる (irr)',9),

  -- Adjectives
  ('Good','いい',12),
  ('Early','はやい',12),
  ('New','おたらしい (い)',12),
  ('Hot (weather / thing)','あつい (い)',12),
  ('Busy (people / days)','いそがしい (い)',12),
  ('Large','おおきい (い)',12),
  ('Interesting / Funny','あもしろい (い)',12),
  ('Good-looking','かっこいい (い conjugates like いい)',12),
  ('Frightening','こわい (い)',12),
  ('Cold (weather - not things)','さむい (い)',12),
  ('Fun','たのしい (い)',12),
  ('Small','ちいさい (い)',12),
  ('Boring','つまらない (い)',12),
  ('Old (thing - not person)','ふるい (い)',12),
  ('Difficult','むざかしい (い)',12),
  ('Easy (problem) / Kind (person)','やさしい (い)',12),
  ('Inexpensive / Cheap (thing)','やすい (い)',12),
  ('Disgusted with / To dislike','きらい (な)',12),
  ('Beautiful / Clean','きれい (な)',12),
  ('Healthy / Energetic','げんき (な)',12),
  ('Quiet','しずか (な)',12),
  ('Fond of / To like','すき (な)',12),
  ('To hate','だいきらい (な)',12),
  ('Very fond of / To love','だいすき (な)',12),
  ('Lively','にぎやか (な)',12),
  ('Not busy / To have a lot of free time','ひま (な)',12),
  ('Tough (situation)','たいへん (な)',12),
  ('Straight','まっすぐ (な)',12),

  -- Adverbs
  ('Not much','あまり (+ negative)',11),
  ('Not at all','せんせん　(+ negative)',11),
  ('Usually','たいてい',11),
  ('A little','ちょっと',11),
  ('Sometimes','ときどき',11),
  ('Always','いつも',11),
  ('Often / Much','よく',11),
  ('About (approximate measurement)','~ぐらい',11),
  ('So / Therefore','だから',11),
  ('Many / A lot','たくさん',11),
  ('Together with (a person)','~と',11),
  ('Alone','ひどりて',11),
  ('Together','いっしょに',11),
  ('Extremely','すごく',11),
  ('Very','とても',11),
  ('[counter for flat objects]','~まい',11),
  ('To (a place) / As far as (a place) / Till (a time)','~まて',11),
  ('Later on','あとて',11),
  ('(Do something) late','おそく',11),

  -- Numbers
  ('0','れい／ゼロ',10),
  ('1','いち',10),
  ('2','に',10),
  ('3','さん',10),
  ('4','よん／じ／（よ）',10),
  ('5','ご',10),
  ('6','ろく',10),
  ('7','なな／しち',10),
  ('8','はち',10),
  ('9','きゅう／く',10),
  ('10','じゅう',10),
  ('11','じゅういち',10),
  ('12','じゅうに',10),
  ('13','じゅうさん',10),
  ('14','じゅうよん／じゅうし',10),
  ('15','じゅうご',10),
  ('16','じゅうろく',10),
  ('17','じゅうなな／じゅうしち',10),
  ('18','じゅうはち',10),
  ('19','じゅうきゅう／じゅうく',10),
  ('20','にじゅう',10),
  ('30','さんじゅう',10),
  ('40','よんじゅう',10),
  ('50','ごじゅう',10),
  ('60','ろくじゅう',10),
  ('70','ななじゅう',10),
  ('80','はちじゅう',10),
  ('90','きゅうじゅう',10),
  ('100','ひゃく',10),
  ('200','にひゃく',10),
  ('300','さんびゃく',10),
  ('400','よんひゃく',10),
  ('500','ごひゃく',10),
  ('600','ろっぴゃく',10),
  ('700','ななひゃく',10),
  ('800','はっぴゃく',10),
  ('900','きゅうひゃく',10),
  ('1000','せん',10),
  ('2000','にせん',10),
  ('3000','さんぜん',10),
  ('4000','よんせん',10),
  ('5000','ごせん',10),
  ('6000','ろくせん',10),
  ('7000','ななせん',10),
  ('8000','はっせん',10),
  ('9000','きゅうせん',10),
  ('10,000','いちまん',10),
  ('20,000','にまん',10),
  ('30,000','さんまん',10),
  ('40,000','よんまん',10),
  ('50,000','ごまん',10),
  ('60,000','ろくまん',10),
  ('70,000','ななまん',10),
  ('80,000','はちまん',10),
  ('90,000','きゅうまん',10),

  ('1','一',13),
  ('1 O´clock','一時',13),
  ('2','二',13),
  ('3 O´clock','二時',13),
  ('4','四',13),
  ('5','五',13),
  ('6','六',13),
  ('7','七',13),
  ('8','八',13),
  ('9','九',13),
  ('10','十',13),
  ('100','百',13),
  ('1000','千',13),
  ('10,000','万',13),
  ('100,000','十万',13),
  ('1,000,000','百万',13),
  ('Yen / Circle','円',13),
  ('Time','時',13),
  ('Day / Sun','日',13),
  ('Japan','日本',13),
  ('Sunday','日曜日',13),
  ('Book','本',13),
  ('Japanese (people)','日本人',13),
  ('Alone','一人で',13),
  ('This person','この人',13),
  ('Moon / Month','月',13),
  ('Monday','月曜日',13),
  ('January','一月',13),
  ('Tuesday','火曜日',13),
  ('Fire','火',13),
  ('Water','水',13),
  ('Wednesday','水曜日',13),
  ('Tree','木',13),
  ('Thursday','木曜日',13),
  ('Gold / Money','金',13),
  ('Friday','金曜日',13),
  ('Soil','土',13),
  ('Saturday','土曜日',13),
  ('Weekday','曜',13),
  ('Sunday','日曜日',13),
  ('Up / Above','上',13),
  ('Down / Under','下',13),
  ('Middle / Inside','中',13),
  ('Half','半',13),
  ('Half past three','三時半',13),
  ('Mountain','山',13),
  ('Mr. / Mrs. Yamakawa','山川さん',13),
  ('River','川',13),
  ('Origin','元',13),
  ('Fine','元気な',13),
  ('Spirit','気',13),
  ('Weather','天気',13),
  ('Heaven','天',13),
  ('I / Private','私',13),
  ('Now','今',13),
  ('Today','今日',13),
  ('Rice field','田',13),
  ('Mr. / Mrs. Tanaka','田中さん',13),
  ('Mr. / Mrs. Yamada','山田さん',13),
  ('Woman','女',13),
  ('Woman (person)','女の人',13),
  ('Man','男',13),
  ('Man (person)','男の人',13),
  ('To see','見る',13),
  ('To go','行く',13),
  ('To eat','食べる',13),
  ('To drink','飲む',13),
  ('East','東',13),
  ('West','西',13),
  ('South','南',13),
  ('North','北',13),
  ('North exit','北口',13),
  ('Mouth','口',13),
  ('To exit','出る',13),
  ('Exit','出口',13),
  ('Right','右',13),
  ('Left','左',13),
  ('Minute / To divide','分',13),
  ('5 minutes','五分',13),
  ('Teacher','先生',13),
  ('Ahead','先',13),
  ('Birth','生',13),
  ('Student','学生',13),
  ('College student','大学生',13),
  ('Big','大きい',13),
  ('Learning','学',13),
  ('University','大学',13),
  ('Outside','外',13),
  ('Foreigner','外国人',13),
  ('Foreign country','外国人',13),
  ('Country','国',13),
  ('China','中国',13);

# --- !Downs
DELETE FROM vocable;