# --- !Ups
DELETE FROM vocable;
INSERT INTO `vocable` (`question`, `answer`, `category_id`)
  VALUES
  -- Things
  ('pencil','えんぴつ',1),
  ('umbrella','かさ',1),
  ('bag','かばん',1),
  ('shoes','かつ',1),
  ('wallet','さいふ',1),
  ('jeans','ジーンズ',1),
  ('dictionary','じしょ',1),
  ('bicycle','じてんしゃ',1),
  ('newspaper','しんぶん',1),
  ('t-shirt','Tシャツ',1),
  ('watch / clock','とけい',1),
  ('notebook','ノート',1),
  ('pen','ペン',1),
  ('hat / cap','ぼおし',1),
  ('book','ほん',1),
  ('you','あなた',1),
  ('chair','いす',1),
  ('dog','いぬ',1),
  ('souvenir','おみやげ',1),
  ('child','こども',1),
  ('rice / meal','ごはん',1),
  ('picture / photograph','しゃしん',1),
  ('desk','つくえ',1),
  ('letter','てがみ',1),
  ('cat','ねく',1),
  ('bread','パン',1),
  ('person','ひと',1),
  ('e-mail','メール',1),

  -- Verbs
  ('to eat (dictionary form)','たべる',2),
  ('to watch (dictionary form)','みる',2),
  ('to get up (dictionary form)','おきる',2),
  ('to read (dictionary form)','よむ',2),
  ('to listen (dictionary form)','きく',2),
  ('to go (dictionary form)','いく',2),
  ('to return (dictionary form)','かえる',2),
  ('to drink (dictionary form)','のむ',2),
  ('to speak (dictionary form)','はなす',2),
  ('to do (dictionary form)','する',2),
  ('to come (dictionary form)','くる',2),
  ('to eat (present affirmative)','たべます',2),
  ('to watch (present affirmative)','みます',2),
  ('to get up (present affirmative)','おきます',2),
  ('to sleep (present affirmative)','ねます',2),
  ('to sleep (dictionary form)','ねる',2),
  ('to read (present affirmative)','よみます',2),
  ('to listen (present affirmative)','ききます',2),
  ('to go (present affirmative)','いきます',2),
  ('to return (present affirmative)','かえります',2),
  ('to drink (present affirmative)','のみます',2),
  ('to speak (present affirmative)','はなします',2),
  ('to do (present affirmative)','します',2),
  ('to come (present affirmative)','きます',2),

  ('to meet / to see (a person) (dictionary form)','あう',2),
  ('to meet / to see (a person) (present affirmative)','あいます',2),
  ('there is... (dictionary form)','ある',2),
  ('there is... (present affirmative)','あります',2),
  ('to buy (dictionary form)','かう',2),
  ('to buy (present affirmative)','かいます',2),
  ('to write (dictionary form)','かく',2),
  ('to write (present affirmative)','かきます',2),
  ('to take (a picture) (dictionary form)','とる',2),
  ('to take (a picture) (present affirmative)','とります',2),
  ('to wait (dictionary form)','まつ',2),
  ('to wait (present affirmative)','きちます',2),
  ('to understand (dictionary form)','わかる',2),
  ('to understand (present affirmative)','わかります',2),


  ('(a person) is in... stays at... (dictionary form)','いる',2),

  -- Entertainment
  ('movie','えいが',3),
  ('music','おんがく',3),
  ('magazine','ざっし',3),
  ('sports','スポーツ',3),
  ('tennis','テニス',3),
  ('date','デート',3),
  ('tv','テレビ',3),

  -- Food & Drinks
  ('ice cream','アイスクリーム',4),
  ('breakfast','おさごはん',4),
  ('sake / alcohol','おさけ',4),
  ('green tea','おちゃ',4),
  ('coffee','コーヒー',4),
  ('dinner','ばんごはん',4),
  ('hamburger','ハンバーガー',4),
  ('lunch','ひるごはん',4),
  ('water','みず',4),
  ('delicious','おいしい',4),
  ('fish','さかな',1),
  ('pork cutlet','とんかつ',4),
  ('meat','にく',4),
  ('menu','メニュー',4),
  ('vegetable','やさい',4),

  -- Places
  ('home / house','いえ',5),
  ('my place / home / house','うち',5),
  ('school','がっこう',5),
  ('cafe','きっさてん',5),
  ('bank','ぎんこう',5),
  ('toilet / restroom','トイレ',5),
  ('library','としょかん',5),
  ('post office','ゆうびんきょく',5),
  ('temple','おてら',5),
  ('park','こうえん',5),
  ('supermarket','スーパー',5),
  ('department store','デパート',5),
  ('bus stop','バスてい',5),
  ('hospital','びょういん',5),
  ('hotel','ホテル',5),
  ('bookstore','ほんや',5),
  ('town / city','まち',5),
  ('restaurant','レストラン',5),

  -- Time expressions
  ('morning','あさ',6),
  ('tomorrow','あした',6),
  ('when','いつ',6),
  ('today','きょう',6),
  ('at about...','ごろ',6),
  ('tonight','こんばん',6),
  ('weekend','しゅうまつ',6),
  ('saturday','どようび',6),
  ('sunday','にちようび',6),
  ('every day','まいにち',6),
  ('every night','まいばん',6),
  ('yesterday','きのう',6),
  ('...hours','じかん',6),
  ('one hour','いちじかん',6),
  ('last week','せんしょう',6),
  ('when... at the time of...','とき',6),
  ('monday','げつようび',6),
  ('tuesday','かようび',6),
  ('wednesday','すいようび',6),
  ('thursday','もくようび',6),
  ('friday','きんようび',6),

  -- Adjectives
  ('good','いい',7),
  ('early','はやい',7),

  -- Adverbs
  ('not much','あまり',8),
  ('no at all','ぜんぜん',8),
  ('usually','たいてい',8),
  ('a little','ちょっと',8),
  ('sometimes','ときどき',8),
  ('often / much','よく',8),
  ('about (approximate measurement)','ぐらい',8),
  ('so / therefore','だから',8),
  ('many / a lot','たくさん',8),
  ('together with (a person)','と',8),
  ('why','どうして',8),
  ('alone','ひとりで',8),

  -- Expressions / Greetings
  ('that`s right / let me see','そうですね',9),
  ('but','でも',9),
  ('how about / how is','どうですか',9),
  ('good morning','おはよう　ございます',9),
  ('good afternoon','こんいちは',9),
  ('good evening','こんばんは',9),
  ('good-bye','さようなら',9),
  ('good night','おやすみなさい',9),
  ('thank you','ありがとう　ございます',9),
  ('excuse me / sorry','すみません',9),
  ('no / not at all','いいえ',9),
  ('ill go and come back','いってきます',9),
  ('please go and come back','いってらっしゃい',9),
  ('im home','ただいま',9),
  ('welcome home','おかえりなさい',9),
  ('thank you for the meal (before eating)','いただきます',9),
  ('thank you for the meal (after eating)','ごちそうさまでした',9),
  ('how do you do?','はじめまして',9),
  ('nice to meet you','よろしく　おねがいします',9),
  ('im sorry','ごめなさい',9),
  ('welcome (to our store)','いらっしゃいませ',9),
  ('... please','を　おねがいします',9),
  ('please give me ...','を　ください',9),
  ('then ... / if that is the case ...','じゃあ',9),
  ('please / here it is','どうぞ',9),
  ('thank you','どうも',9),

  -- Numbers
  ('0','れい／ゼロ',10),
  ('1','いち',10),
  ('2','に',10),
  ('3','さん',10),
  ('4','よん／じ／（よ）',10),
  ('5','ご',10),
  ('6','ろく',10),
  ('7','なな／しち',10),
  ('8','はち',10),
  ('9','きゅう／く',10),
  ('10','じゅう',10),
  ('11','じゅういち',10),
  ('12','じゅうに',10),
  ('13','じゅうさん',10),
  ('14','じゅうよん／じゅうし',10),
  ('15','じゅうご',10),
  ('16','じゅうろく',10),
  ('17','じゅうなな／じゅうしち',10),
  ('18','じゅうはち',10),
  ('19','じゅうきゅう／じゅうく',10),
  ('20','にじゅう',10),
  ('30','さんじゅう',10),
  ('40','よんじゅう',10),
  ('50','ごじゅう',10),
  ('60','ろくじゅう',10),
  ('70','ななじゅう',10),
  ('80','はちじゅう',10),
  ('90','きゅうじゅう',10),
  ('100','ひゃく',10),
  ('200','にひゃく',10),
  ('300','さんびゃく',10),
  ('400','よんひゃく',10),
  ('500','ごひゃく',10),
  ('600','ろっぴゃく',10),
  ('700','ななひゃく',10),
  ('800','はっぴゃく',10),
  ('900','きゅうひゃく',10),
  ('1000','せん',10),
  ('2000','にせん',10),
  ('3000','さんぜん',10),
  ('4000','よんせん',10),
  ('5000','ごせん',10),
  ('6000','ろくせん',10),
  ('7000','ななせん',10),
  ('8000','はっせん',10),
  ('9000','きゅうせん',10),
  ('10,000','いちまん',10),
  ('20,000','にまん',10),
  ('30,000','さんまん',10),
  ('40,000','よんまん',10),
  ('50,000','ごまん',10),
  ('60,000','ろくまん',10),
  ('70,000','ななまん',10),
  ('80,000','はちまん',10),
  ('90,000','きゅうまん',10),

  -- Kanji
  ('1','一',11),
  ('2','二',11),
  ('3','三',11),
  ('4','四',11),
  ('5','五',11),
  ('6','六',11),
  ('7','七',11),
  ('8','八',11),
  ('9','九',11),
  ('10','十',11),
  ('100','百',11),
  ('1000','千',11),
  ('10,000','万',11),
  ('yen','円',11),
  ('time','時',11),

  ('day / sun','日',11),
  ('book / basis','本',11),
  ('person','人？',11),
  ('moon / month','月',11),
  ('fire','火',11),
  ('water','水',11),
  ('tree','木',11),
  ('gold / money','金',11),
  ('soil','土',11),
  ('up','上',11),
  ('weekday','?',11),
  ('down','下',11),
  ('middle','中',11),
  ('half','半',11),



  -- Katakana
  ('a','ア',12),
  ('i','イ',12),
  ('u','ウ',12),
  ('e','エ',12),
  ('o','オ',12),
  ('ka','カ',12),
  ('ki','キ',12),
  ('ku','ク',12),
  ('ke','ケ',12),
  ('ko','コ',12),
  ('sa','サ',12),
  ('shi','シ',12),
  ('su','ス',12),
  ('se','セ',12),
  ('so','ソ',12),
  ('ta','タ',12),
  ('chi','チ',12),
  ('tsu','ツ',12),
  ('te','テ',12),
  ('to','ト',1),
  ('na','ナ',12),
  ('ni','ニ',12),
  ('nu','ヌ',12),
  ('ne','ネ',12),
  ('no','ノ',12),
  ('ha','ハ',12),
  ('hi','ヒ',12),
  ('fu','フ',12),
  ('he','ヘ',12),
  ('ho','ホ',12),
  ('ma','マ',12),
  ('mi','ミ',12),
  ('mu','ム',12),
  ('me','メ',12),
  ('mo','モ',12),
  ('ya','ヤ',12),
  ('yu','ユ',12),
  ('yo','ヨ',12),
  ('ra','ラ',12),
  ('ri','リ',12),
  ('ru','ル',12),
  ('re','レ',12),
  ('ro','ロ',12),
  ('wa','ワ',12),
  ('o','オ',12),
  ('n','ン',12),
  ('ga','ガ',12),
  ('gi','ギ',12),
  ('gu','グ',12),
  ('ge','ゲ',12),
  ('go','ゴ',12),
  ('za','ザ',12),
  ('ji','ジ',12),
  ('zu','ズ',12),
  ('ze','ゼ',12),
  ('zo','ゾ',12),
  ('da','ダ',12),
--   ('ji','ー',12),
--   ('zu','ー',12),
  ('de','デ',12),
  ('do','ド',12),
  ('ba','バ',12),
  ('bi','ビ',12),
  ('bu','ブ',12),
  ('be','ベ',12),
  ('bo','ボ',12),
  ('pa','パ',12),
  ('pi','ピ',12),
  ('pu','プ',12),
  ('pe','ペ',12),
  ('po','ポ',12),
  ('kya','キャ',12),
  ('kyu','キュ',12),
  ('kyo','キョ',12),
  ('sha','シャ',12),
  ('shu','シュ',12),
  ('she','シェ',12),
  ('sho','ショ',12),
  ('cha','チャ',12),
  ('chu','チュ',12),
  ('che','チェ',12),
  ('cho','チョ',12),
  ('nya','ニャ',12),
  ('nyu','ニュ',12),
  ('nyo','ニョ',12),
  ('hya','ヒャ',12),
  ('hyu','ヒュ',12),
  ('hyo','ヒョ',12),
  ('mya','ミャ',12),
  ('myu','ミュ',12),
  ('myo','ミョ',12),
  ('rya','リャ',12),
  ('ryu','リュ',12),
  ('ryo','リョ',12),
  ('gya','ギャ',12),
  ('gyu','ギュ',12),
  ('gyo','ギョ',12),
  ('ja','ジャ',12),
  ('ju','ジュ',12),
  ('jo','ジョ',12),
  ('bya','ビャ',12),
  ('byu','ビュ',12),
  ('byo','ビョ',12),
  ('pya','ピャ',12),
  ('pyu','ピュ',12),
  ('pyo','ピョ',12),
  ('wi','ウィ',12),
  ('we','ウェ',12),
--   ('wo','ー',12),
  ('tsa','ツァ',12),
  ('tsi','ツィ',12),
  ('tse','ツェ',12),
  ('tso','ツォ',12),
--   ('ti','ー',12),
  ('fa','ファ',12),
  ('fi','フィ',12),
  ('fyu','フュ',12),
  ('fe','フェ',12),
  ('fo','フォ',12),
--   ('di','ー',12),
  ('dyu','ヂュ',12),
  ('va','ヴァ',12),
  ('vi','ヴィ',12),
  ('vu','ヴ',12),
  ('ve','ヴェ',12),
  ('vo','ヴォ',12),

  -- Nouns
  ('part-time job','アレバイト',13),
  ('shopping','かいもの',13),
  ('class','クラス',13),

  -- Location words
  ('right','みぎ',14),
  ('left','ひだり',14),
  ('front','まえ',14),
  ('back','うしろ',14),
  ('inside','なか',14),
  ('on','うえ',14),
  ('under','した',14),
  ('near / nearby','らかく',14),
  ('next (to)','となり',14),
  ('between','あいだ',14),

  -- In the classroom
  ('Do you understand?','わかりましたか',15),
  ('I understand / I understood','わかりました',15),
  ('I dont undertand / I dont know','わかりません',15),
  ('Please say it slowly','ゆっくりいってください',15),
  ('Please say it again','もおいちどいってください',15),
  ('Please wait','ちょっとまってください',15),
  ('Please listen / Please ask','きいてください',15),
  ('Please look at page 10','じゅうぺじをみてください',15),

  -- Words that point
  ('this one','これ',16),
  ('that one','それ',16),
  ('that one (over there)','あれ',16),
  ('which one','ぢれ',16),
  ('this ...','この',16),
  ('that ...','その',16),
  ('that ... (over there)','あの',16),
  ('which ...','どの',16),
  ('here','ここ',16),
  ('there','そこ',16),
  ('over there','あそこ',16),
  ('where','どこ',16),
  ('who','だれ',16),

  -- Money matters
  ('how much','いくら',17),
  ('... yen','えん',17),
  ('expensive / high','たかい',17),

  -- Occupations
  ('job / work / occupation','しごと',18),
  ('doctor','いしゃ',18),
  ('office worker','かいしゃいん',18),
  ('high school student','こうこうせい',18),
  ('housewife','しゅふ',18),
  ('graduate student','だいがくいんせい',18),
  ('college student','だいがくせい',18),
  ('lawyer','べんごし',18),

  -- Family
  ('mother','おかあさん',19),
  ('father','おとうさん',19),
  ('older sister','おねえさん',19),
  ('older brother','おにいさん',19),
  ('younger sister','いもうと',19),
  ('younger brother','おとうと',19),

  -- Majors
  ('science','かがく',20),
  ('asian studies','アジアけんきゅ',20),
  ('economics','けいざい',20),
  ('international relations','こくさいかんけい',20),
  ('computer','こんぴゅうたあ',20),
  ('anthropology','じんるいがく',20),
  ('politics','せいじ',20),
  ('business','びじねす',20),
  ('literature','ぶんがく',20),
  ('history','れきし',20);

# --- !Downs
DELETE FROM vocable;